### ISSUE TITLE
BOSS箱子的高級武器過於常見 希望在寶箱內有更多組合 

### ISSUE THREAD

**Issue by bksesame** [dungeoncraft-mc/dungeoncraft#112]
**建議的敘述**

**補充圖片**
![image](https://user-images.githubusercontent.com/85820201/129767775-2ef5e1a2-580d-4747-b959-c0ab95e97c97.png)

**額外補充**

**Comment by KanekiAkira** [comment]
現在稀有度還可以，高級武器過於常見主要原因Boss難度，獲取武器過於容易
