### ISSUE TITLE
有些陶罐會隱形

### ISSUE THREAD

**Issue by apollogauss** [dungeoncraft-mc/dungeoncraft#123]
遊戲 ID: 

**敘述 Bug**
陶罐的模型消失了，場上有時候會出現很多隱形陶罐

**正常情況下的預期行為(選填)**
陶罐應該會有模型

**Bug 再現步驟**
打完任意圖騰怪物

**問題截圖(選填)**
![image](https://user-images.githubusercontent.com/48764927/129856903-863a93e9-e7d8-4f09-b629-ee0b593609c2.png)

**電腦資訊:**
 Windows10

**額外補充**
額外補充其他事項

**Comment by apollogauss** [comment]
有時候還會生成無敵陶罐

**Comment by CactusMikaz** [comment]
因為玩家的武器是劍，所以劍的劍氣揮到目標陶罐以外的陶罐會造成隱形
