### ISSUE TITLE
在地城對門衛使用武器技能(迴旋斬)後，會導致無法結束戰鬥狀態

### ISSUE THREAD

**Issue by KanekiAkira** [dungeoncraft-mc/dungeoncraft#127]
![image](https://user-images.githubusercontent.com/69110846/130109070-93ca6edc-801b-41fc-aadc-8176c373d46b.png)
![image](https://user-images.githubusercontent.com/69110846/130109126-441e4870-722c-4354-9147-5f792c762e9f.png)

**Comment by CactusMikaz** [comment]
應該不是迴旋展觸發
