### ISSUE TITLE
新玩家登入的重生點沒有設定

### ISSUE THREAD

**Issue by apollogauss** [dungeoncraft-mc/dungeoncraft#50]
遊戲 ID: apollogauss

**敘述 Bug**
在此清楚說明 Bug 

我重生在一個不正確的世界

**正常情況下的預期行為(選填)**
正常情況下應該發生的反饋

重生在關卡起點

**Bug 再現步驟**
Bug 的製造流程

第一次登入遊戲

**問題截圖(選填)**
在此貼上圖片輔助敘述 Bug

![image](https://user-images.githubusercontent.com/48764927/126055762-e22b3a17-1ec9-463e-ac0d-17949b4207c5.png)

**電腦資訊:**
 - 作業系統: 例: Windows10

**額外補充**
額外補充其他事項

**Comment by CactusMikaz** [comment]
不確定是不是嚴謹意義上的新玩家
嚴謹意義的新玩家應該是，在登入之前完全沒有角色檔
