### ISSUE TITLE
陶罐獎勵有時候有，有時候沒有

### ISSUE THREAD

**Issue by apollogauss** [dungeoncraft-mc/dungeoncraft#60]
遊戲 ID: 

**敘述 Bug**
在此清楚說明 Bug 

**正常情況下的預期行為(選填)**
正常情況下應該發生的反饋

**Bug 再現步驟**
Bug 的製造流程

**問題截圖(選填)**
在此貼上圖片輔助敘述 Bug

**電腦資訊:**
 - 作業系統: 例: Windows10

**額外補充**
額外補充其他事項

**Comment by CactusMikaz** [comment]
回報給官方了，問問啥問題

**Comment by CactusMikaz** [comment]
每次開服之後都需要mm reload讓 MMOItems的道具跟MM的Droptable連接起來
