### ISSUE TITLE
寶箱獎勵、怪物掉落物都有機會被其他玩家吸走

### ISSUE THREAD

**Issue by apollogauss** [dungeoncraft-mc/dungeoncraft#61]
遊戲 ID: 

**敘述 Bug**
在此清楚說明 Bug 

**正常情況下的預期行為(選填)**
正常情況下應該發生的反饋

**Bug 再現步驟**
Bug 的製造流程

**問題截圖(選填)**
在此貼上圖片輔助敘述 Bug

**電腦資訊:**
 - 作業系統: 例: Windows10

**額外補充**
額外補充其他事項

**Comment by CactusMikaz** [comment]
寶箱的獎勵生成位置變成在觸發者身上，可能可以改善此問題

**Comment by CactusMikaz** [comment]
還是有問題

**Comment by CactusMikaz** [comment]
裝了pandeloot，應該不會再看到其他玩家的掉落物
