### ISSUE TITLE
玩家會被武器的燃燒特效傷害

### ISSUE THREAD

**Issue by apollogauss** [dungeoncraft-mc/dungeoncraft#65]
遊戲 ID: 

**敘述 Bug**
在此清楚說明 Bug 

**正常情況下的預期行為(選填)**
正常情況下應該發生的反饋

**Bug 再現步驟**
Bug 的製造流程

**問題截圖(選填)**
在此貼上圖片輔助敘述 Bug

**電腦資訊:**
 - 作業系統: 例: Windows10

**額外補充**
額外補充其他事項

**Comment by CactusMikaz** [comment]
Are you sure it's due to MMOItems? That MI ability only sets the initial ability target on fire, it doesn't apply an AoE burn. Are you sure it's not because being hit by a burning monster will set you on fire as well?

可能是技能點燃怪物之後，第二個玩家被燃燒的怪物打中導致燃燒

**Comment by CactusMikaz** [comment]
發現各種道具技能都會對其他玩家造成影響，雖然沒有傷害但是可以擊飛玩家之類的。

**Comment by CactusMikaz** [comment]
無法解決，先CLOSE
