### ISSUE TITLE
一般玩家沒有OP的狀況下 latour的雙擊拿取自定義方塊可以被使用  也可以用自訂義方塊建築

### ISSUE THREAD

**Issue by bksesame** [dungeoncraft-mc/dungeoncraft#74]
遊戲 ID: 

**敘述 Bug**
在此清楚說明 Bug 

**正常情況下的預期行為(選填)**
正常情況下應該發生的反饋

**Bug 再現步驟**
Bug 的製造流程

**問題截圖(選填)**
在此貼上圖片輔助敘述 Bug
![螢幕擷取畫面 2021-07-20 205123](https://user-images.githubusercontent.com/85820201/126327338-5ea59cf0-2a8c-4c9d-8c83-05af57015c15.png)

**電腦資訊:**
 - 作業系統: 例: Windows10

**額外補充**
額外補充其他事項

**Comment by Cyanide2489** [comment]
已確認問題，目前的暫時解決方案是限定 OP 身分操作
