### ISSUE TITLE
在地城內選單內 一般玩家無法使用下一關的功能

### ISSUE THREAD

**Issue by bksesame** [dungeoncraft-mc/dungeoncraft#79]
遊戲 ID: 

**敘述 Bug**
在此清楚說明 Bug 

**正常情況下的預期行為(選填)**
正常情況下應該發生的反饋

**Bug 再現步驟**
Bug 的製造流程

**問題截圖(選填)**
在此貼上圖片輔助敘述 Bug
![螢幕擷取畫面 2021-07-20 210718](https://user-images.githubusercontent.com/85820201/126329438-47b85431-81b1-4a02-88bf-ae37582fe6f1.png)

**電腦資訊:**
 - 作業系統: 例: Windows10

**額外補充**
額外補充其他事項

**Comment by CactusMikaz** [comment]
重複回報
