### ISSUE TITLE
木乃伊王在無防具的狀態下太痛了 一下就沒了

### ISSUE THREAD

**Issue by bksesame** [dungeoncraft-mc/dungeoncraft#84]
遊戲 ID: 

**敘述 Bug**
在此清楚說明 Bug 

**正常情況下的預期行為(選填)**
正常情況下應該發生的反饋
邏輯商不應該一下就死亡

**Bug 再現步驟**
Bug 的製造流程
打木乃伊王

**問題截圖(選填)**
在此貼上圖片輔助敘述 Bug
![螢幕擷取畫面 2021-07-25 182153](https://user-images.githubusercontent.com/85820201/126895823-78d00163-777a-4c95-9927-f831835934cc.png)

**電腦資訊:**
 - 作業系統: 例: Windows10

**額外補充**
額外補充其他事項

**Comment by CactusMikaz** [comment]
傷害已經下調，未來會加入裝備防具
