### ISSUE TITLE
字卡掉落率過高

### ISSUE THREAD

**Issue by KanekiAkira** [dungeoncraft-mc/dungeoncraft#85]
現在每種卡片掉落均為5%，共7種，總機率35%
建議將總機率下調到10~15%，並依照任務需求調整字卡的個別掉落機率，在維持總機率10%~15%的情況下，將有複數任務的字卡機率調高，單獨則調低

**Comment by CactusMikaz** [comment]
先試試看改成2.5%

**Comment by CactusMikaz** [comment]
藥水機率也順便下降成2.5%
