### ISSUE TITLE
與兩種門衛互動都沒有出現對話選項

### ISSUE THREAD

**Issue by KanekiAkira** [dungeoncraft-mc/dungeoncraft#87]
![image](https://user-images.githubusercontent.com/69110846/126896108-f5510669-e98d-4fb6-90ea-281403e46b7b.png)
猜測觸發條件是在與"下一關的門衛"對話時，快速點擊右鍵，導致在對話結束後，前往下一層的瞬間觸發到第二次對話，並沒有選擇回應

**Comment by CactusMikaz** [comment]
在對話完成的時候，但尚未傳送期間對NPC連點，會導致從頭觸發對話進入到對話選擇狀態無法退出
