### ISSUE TITLE
生成了殭屍騎士的小雞且無法殺死 造成實體資源浪費

### ISSUE THREAD

**Issue by bksesame** [dungeoncraft-mc/dungeoncraft#88]
遊戲 ID: 

**敘述 Bug**
在此清楚說明 Bug 

**正常情況下的預期行為(選填)**
正常情況下應該發生的反饋

**Bug 再現步驟**
Bug 的製造流程
擊殺怪物會出現

**問題截圖(選填)**
在此貼上圖片輔助敘述 Bug
![螢幕擷取畫面 2021-07-25 184656](https://user-images.githubusercontent.com/85820201/126896444-60a3bb9a-772e-41ae-b800-8b659fb28050.png)

**電腦資訊:**
 - 作業系統: 例: Windows10

**額外補充**
額外補充其他事項

**Comment by CactusMikaz** [comment]
要加上prevent jocky
