### ISSUE TITLE
希望匕首投擲的時間在減少0.3~0.5秒 

### ISSUE THREAD

**Issue by bksesame** [dungeoncraft-mc/dungeoncraft#90]
**建議的敘述**
在打擊連貫的上面 匕首是攻速很快的物件 
現在耐力被改動的狀態下 希望匕首因為耐力的限制能夠開放攻擊的速度
**補充圖片**

**額外補充**

**Comment by CactusMikaz** [comment]
耐力消耗再加1，冷卻調整成1
